### ISSUE TITLE
Some of device_names are not available from the API.

### ISSUE THREAD

**Issue by mcc311** [qqaatw/LibJciHitachi#13]
Description:

I encountered an issue when trying to connect my dehumidifier using the provided documentation examples. I attempted to establish a connection using both the legacy API and the AWS API.

```Python
from JciHitachi.api import JciHitachiAPI
# from JciHitachi.api import JciHitachiAWSAPI
# Login
api = JciHitachiAPI(EMAIL, PASSWORD, DEVICENAME)
# api = JciHitachiAWSAPI(EMAIL, PASSWORD, DEVICENAME)
api.login()

# Check device status
# device_status = api.get_status(legacy=True) # return legacy status class
device_status = api.get_status()
print(device_status[DEVICENAME].status)
```

**Error Message:**
Upon executing the code, I received the following error:
```bash
AssertionError: Some of device_names are not available from the API.
```

**Full traceback:**
```bash
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
[/Users/mcc_311/Desktop/playground/test.ipynb](https://file+.vscode-resource.vscode-cdn.net/Users/mcc_311/Desktop/playground/test.ipynb) 儲存格 19 in ()
      [1](vscode-notebook-cell:/Users/mcc_311/Desktop/playground/test.ipynb#X24sZmlsZQ%3D%3D?line=0) # Login
      [2](vscode-notebook-cell:/Users/mcc_311/Desktop/playground/test.ipynb#X24sZmlsZQ%3D%3D?line=1) api = JciHitachiAPI(EMAIL, PASSWORD, DEVICENAME)
----> [3](vscode-notebook-cell:/Users/mcc_311/Desktop/playground/test.ipynb#X24sZmlsZQ%3D%3D?line=2) api.login()
      [5](vscode-notebook-cell:/Users/mcc_311/Desktop/playground/test.ipynb#X24sZmlsZQ%3D%3D?line=4) # Check device status
      [6](vscode-notebook-cell:/Users/mcc_311/Desktop/playground/test.ipynb#X24sZmlsZQ%3D%3D?line=5) # device_status = api.get_status(legacy=True) # return legacy status class
      [7](vscode-notebook-cell:/Users/mcc_311/Desktop/playground/test.ipynb#X24sZmlsZQ%3D%3D?line=6) device_status = api.get_status()

File [/opt/anaconda3/lib/python3.9/site-packages/JciHitachi/api.py:377](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/lib/python3.9/site-packages/JciHitachi/api.py:377), in JciHitachiAPI.login(self)
    374     self._user_id = conn_json["results"][0]["Owner"]
    376 # peripherals
--> 377 self._peripherals = Peripheral.from_device_names(
    378     conn_json,
    379     self.device_names
    380 )
    381 self.device_names = list(self._peripherals.keys())
    383 # mqtt

File [/opt/anaconda3/lib/python3.9/site-packages/JciHitachi/api.py:88](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/lib/python3.9/site-packages/JciHitachi/api.py:88), in Peripheral.from_device_names(cls, peripherals_json, device_names)
     85         if device_type in cls.supported_device_type:
     86             peripherals[device_name] = cls(result)
---> 88 assert device_names is None or len(device_names) == len(peripherals), \
     89     "Some of device_names are not available from the API."
     91 return peripherals

AssertionError: Some of device_names are not available from the API.
Exception ignored in: Exception ignored in: <class 'KeyError'>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/awscrt/mqtt.py", line 628, in callback_wrapper
<class 'KeyError'>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/awscrt/mqtt.py", line 628, in callback_wrapper
    callback(topic=topic, payload=payload, dup=dup, qos=QoS(qos), retain=retain)
  File "/opt/anaconda3/lib/python3.9/site-packages/JciHitachi/aws_connection.py", line 561, in _on_publish
    callback(topic=topic, payload=payload, dup=dup, qos=QoS(qos), retain=retain)
  File "/opt/anaconda3/lib/python3.9/site-packages/JciHitachi/aws_connection.py", line 561, in _on_publish
    self._mqtt_events.device_control_event[thing_name].set()
KeyError: 'ap-northeast-1:f5fb78f7-04b3-418e-aab0-6ee66afadeca_66428598606390'
    self._mqtt_events.device_control_event[thing_name].set()
KeyError: 'ap-northeast-1:f5fb78f7-04b3-418e-aab0-6ee66afadeca_66428598606390'
Exception ignored in: <class 'KeyError'>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/awscrt/mqtt.py", line 628, in callback_wrapper
    callback(topic=topic, payload=payload, dup=dup, qos=QoS(qos), retain=retain)
  File "/opt/anaconda3/lib/python3.9/site-packages/JciHitachi/aws_connection.py", line 561, in _on_publish
    self._mqtt_events.device_control_event[thing_name].set()
KeyError: 'ap-northeast-1:f5fb78f7-04b3-418e-aab0-6ee66afadeca_66428598606390'
Exception ignored in: <class 'KeyError'>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/awscrt/mqtt.py", line 628, in callback_wrapper
    callback(topic=topic, payload=payload, dup=dup, qos=QoS(qos), retain=retain)
  File "/opt/anaconda3/lib/python3.9/site-packages/JciHitachi/aws_connection.py", line 561, in _on_publish
    self._mqtt_events.device_control_event[thing_name].set()
KeyError: 'ap-northeast-1:f5fb78f7-04b3-418e-aab0-6ee66afadeca_66428598606390'
```
**Additional Information:**
- The error seems to point to the Peripheral.from_device_names method in JciHitachi/api.py.
- It seems the program is asserting that some device names aren't available from the API.
- There were also some KeyError exceptions related to the AWS connection.
- Any assistance would be greatly appreciated. Thank you for developing this project; it's fantastic!

**Comment by qqaatw** [comment]
The legacy API is deprecated and no longer covered by tests. Please use the AWS one.

**Comment by mcc311** [comment]
@qqaatw. Yes, I also tried the AWS one, but it turn to be the same error as above.
```python
from JciHitachi.api import JciHitachiAWSAPI
# Login
api = JciHitachiAWSAPI(EMAIL, PASSWORD, DEVICENAME)
api.login()

# Check device status
# device_status = api.get_status(legacy=True) # return legacy status class
device_status = api.get_status()
print(device_status[DEVICENAME].status)
```

with same error message:
```bash
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
[/Users/mcc_311/Desktop/playground/test.ipynb](https://file+.vscode-resource.vscode-cdn.net/Users/mcc_311/Desktop/playground/test.ipynb) 儲存格 19 in ()
      [2](vscode-notebook-cell:/Users/mcc_311/Desktop/playground/test.ipynb#X24sZmlsZQ%3D%3D?line=1) # Login
      [3](vscode-notebook-cell:/Users/mcc_311/Desktop/playground/test.ipynb#X24sZmlsZQ%3D%3D?line=2) api = JciHitachiAWSAPI(EMAIL, PASSWORD, DEVICENAME)
----> [4](vscode-notebook-cell:/Users/mcc_311/Desktop/playground/test.ipynb#X24sZmlsZQ%3D%3D?line=3) api.login()
      [6](vscode-notebook-cell:/Users/mcc_311/Desktop/playground/test.ipynb#X24sZmlsZQ%3D%3D?line=5) # Check device status
      [7](vscode-notebook-cell:/Users/mcc_311/Desktop/playground/test.ipynb#X24sZmlsZQ%3D%3D?line=6) # device_status = api.get_status(legacy=True) # return legacy status class
      [8](vscode-notebook-cell:/Users/mcc_311/Desktop/playground/test.ipynb#X24sZmlsZQ%3D%3D?line=7) device_status = api.get_status()

File [/opt/anaconda3/lib/python3.9/site-packages/JciHitachi/api.py:988](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/lib/python3.9/site-packages/JciHitachi/api.py:988), in JciHitachiAWSAPI.login(self)
    984 conn_status, conn_json = conn.get_data()
    986 if conn_status == "OK":
    987     # things
--> 988     self._things = AWSThing.from_device_names(
    989         conn_json,
    990         self.device_names
    991     )
    992     self.device_names = list(self._things.keys())
    993     thing_names = [value.thing_name for value in self._things.values()]

File [/opt/anaconda3/lib/python3.9/site-packages/JciHitachi/api.py:677](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/lib/python3.9/site-packages/JciHitachi/api.py:677), in AWSThing.from_device_names(cls, things_json, device_names)
    674         if device_type in cls.supported_device_type:
    675             things[device_name] = cls(thing)
--> 677 assert device_names is None or len(device_names) == len(things), \
    678     "Some of device_names are not available from the API."
    680 return things

AssertionError: Some of device_names are not available from the API.
```

**Comment by mcc311** [comment]
@qqaatw Thanks for replying to me so fast.
I also tried the AWS API, but it turns to same error message as above.
```bash
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[/Users/mcc_311/Desktop/playground/test.ipynb](https://file+.vscode-resource.vscode-cdn.net/Users/mcc_311/Desktop/playground/test.ipynb) 儲存格 19 in ()
      [2](vscode-notebook-cell:/Users/mcc_311/Desktop/playground/test.ipynb#X24sZmlsZQ%3D%3D?line=1) # Login
      [3](vscode-notebook-cell:/Users/mcc_311/Desktop/playground/test.ipynb#X24sZmlsZQ%3D%3D?line=2) api = JciHitachiAWSAPI(EMAIL, PASSWORD)
----> [4](vscode-notebook-cell:/Users/mcc_311/Desktop/playground/test.ipynb#X24sZmlsZQ%3D%3D?line=3) api.login()
      [6](vscode-notebook-cell:/Users/mcc_311/Desktop/playground/test.ipynb#X24sZmlsZQ%3D%3D?line=5) # Check device status
      [7](vscode-notebook-cell:/Users/mcc_311/Desktop/playground/test.ipynb#X24sZmlsZQ%3D%3D?line=6) # device_status = api.get_status(legacy=True) # return legacy status class
      [8](vscode-notebook-cell:/Users/mcc_311/Desktop/playground/test.ipynb#X24sZmlsZQ%3D%3D?line=7) device_status = api.get_status()

File [/opt/anaconda3/lib/python3.9/site-packages/JciHitachi/api.py:1016](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/lib/python3.9/site-packages/JciHitachi/api.py:1016), in JciHitachiAWSAPI.login(self)
   1013         raise RuntimeError(f"An error occurred when connecting to MQTT endpoint.")
   1015     # status
-> 1016     self.refresh_status(refresh_support_code=True, refresh_shadow=True)
   1017 else:
   1018     raise RuntimeError(f"An error occurred when retrieving devices info: {conn_status}")

File [/opt/anaconda3/lib/python3.9/site-packages/JciHitachi/api.py:1144](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/lib/python3.9/site-packages/JciHitachi/api.py:1144), in JciHitachiAWSAPI.refresh_status(self, device_name, refresh_support_code, refresh_shadow)
   1141     self._mqtt.publish(self._host_identity_id, thing.thing_name, "status", self._mqtt_timeout)
   1143 # execute
-> 1144 support_results, shadow_results, status_results, _ = self._mqtt.execute()
   1146 # gather results
   1147 for name, thing in self._get_valid_things(device_name):

File [/opt/anaconda3/lib/python3.9/site-packages/JciHitachi/aws_connection.py:933](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/lib/python3.9/site-packages/JciHitachi/aws_connection.py:933), in JciHitachiAWSMqttConnection.execute(self, control)
...
     34         "asyncio.run() cannot be called from a running event loop")
     36 if not coroutines.iscoroutine(main):
     37     raise ValueError("a coroutine was expected, got {!r}".format(main))

RuntimeError: asyncio.run() cannot be called from a running event loop
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?ca94975d-b563-49fe-82a1-b2813e3023f4) or open in a [text editor](command:workbench.action.openLargeOutput?ca94975d-b563-49fe-82a1-b2813e3023f4). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...
MQTT connection was interrupted with exception {error}.
```

And I think I found out the reason. This API cannot be called in a jupyter notebook. As I use the `.py` extension, all work so good. So I think I solve the problem. But still, thanks a lot!

**Comment by qqaatw** [comment]
Glad it works. We refresh and update device statuses asynchronously to speed up the time they take. So running the code in a runtime that runs the code one line at a time could be the cause indeed.
